import { Metadata } from 'next';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { LucideArrowLeft, LucideLock } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Privacy Policy | TruCheq',
  description: 'Privacy Policy for TruCheq — Headless Web3 P2P Commerce Protocol',
};

const LAST_UPDATED = 'March 2025';

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#0A0F14] text-foreground selection:bg-primary selection:text-primary-foreground">
      <div className="fixed inset-0 grid-pattern pointer-events-none opacity-10" />

      {/* Header */}
      <header className="sticky top-0 z-40 border-b border-white/5 bg-black/60 backdrop-blur-md">
        <div className="max-w-2xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/">
            <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-white gap-2">
              <LucideArrowLeft className="w-4 h-4" />
              Back
            </Button>
          </Link>
          <div className="flex items-center gap-2">
            <LucideLock className="w-4 h-4 text-primary" />
            <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Privacy</span>
          </div>
        </div>
      </header>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-4 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-black italic tracking-tighter text-white mb-2">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="max-w-none space-y-6 text-muted-foreground leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">1. Overview</h2>
            <p>TruCheq is designed with a privacy-first architecture. We minimize data collection, use decentralized storage, and employ end-to-end encrypted messaging. This Privacy Policy explains what information we collect, how it&rsquo;s stored, and your rights regarding your data.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">2. Information We Collect</h2>

            <h3 className="text-sm font-bold text-white/80 mt-4">2.1 World ID Verification Data</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Verification level</strong> (Orb or Device) — stored locally on your device and in the World ID zero-knowledge proof system.</li>
              <li><strong>Nullifier hash</strong> — a unique, non-reversible identifier generated by World ID&rsquo;s ZK circuits. This cannot be used to identify you personally.</li>
              <li><strong>TruCheq code</strong> — a human-readable code derived from your nullifier hash for easy sharing.</li>
            </ul>
            <p>TruCheq does <strong>not</strong> collect, store, or have access to your biometric data. All biometric processing happens within the World ID Orb and World App — only zero-knowledge proofs are transmitted.</p>

            <h3 className="text-sm font-bold text-white/80 mt-4">2.2 Wallet Information</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Wallet address</strong> — your public Ethereum address, used to receive payments and identify listings.</li>
              <li>This is public blockchain data and is inherently visible on-chain.</li>
            </ul>

            <h3 className="text-sm font-bold text-white/80 mt-4">2.3 Listing Data</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Item name, description, price, images</strong> — provided by sellers when creating listings.</li>
              <li>This data is stored on IPFS (see Section 4) and is publicly accessible via the listing link.</li>
            </ul>

            <h3 className="text-sm font-bold text-white/80 mt-4">2.4 Chat Messages</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Messages between buyers and sellers are sent via <strong>XMTP</strong> (Extensible Message Transport Protocol).</li>
              <li>All messages are <strong>end-to-end encrypted</strong>. TruCheq cannot read, store, or access message content.</li>
              <li>Messages are stored on the XMTP network, not on TruCheq servers.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">3. Information We Do NOT Collect</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Biometric data (handled entirely by World ID)</li>
              <li>Personal identification (name, email, phone number)</li>
              <li>Location data</li>
              <li>Browsing history or analytics tracking</li>
              <li>Chat message content (E2E encrypted via XMTP)</li>
              <li>Private keys or seed phrases</li>
              <li>Payment card or bank information</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">4. Data Storage</h2>

            <h3 className="text-sm font-bold text-white/80 mt-4">4.1 IPFS (InterPlanetary File System)</h3>
            <p>Listing metadata and images are stored on IPFS via Filebase. Key characteristics:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Decentralized</strong> — data is not stored on any single server controlled by TruCheq.</li>
              <li><strong>Content-addressed</strong> — data integrity is cryptographically guaranteed by CIDs.</li>
              <li><strong>Public</strong> — anyone with the CID can access the data. Do not include private information in listings.</li>
              <li><strong>Persistent</strong> — data pinned to IPFS may persist indefinitely even if you request deletion.</li>
            </ul>

            <h3 className="text-sm font-bold text-white/80 mt-4">4.2 Local Storage</h3>
            <p>The following data is stored in your browser&rsquo;s localStorage:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Verification status and TruCheq code (for session persistence).</li>
              <li>Wallet address (for auto-reconnection).</li>
              <li>Your created listings (for dashboard display).</li>
            </ul>
            <p>This data never leaves your device and can be cleared at any time by clearing browser data or using the in-app logout function.</p>

            <h3 className="text-sm font-bold text-white/80 mt-4">4.3 Blockchain</h3>
            <p>Payment transactions are recorded on public blockchains (Base, World Chain). This data includes:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Sender and receiver wallet addresses.</li>
              <li>Transaction amounts and token types.</li>
              <li>Transaction hashes and timestamps.</li>
            </ul>
            <p>This is inherent to public blockchain infrastructure and cannot be removed or hidden by TruCheq.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">5. Data Sharing</h2>
            <p>TruCheq does not sell, rent, or share your personal data with third parties. Specifically:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>We do not share verification data beyond what World ID&rsquo;s zero-knowledge proof system provides.</li>
              <li>We do not share chat content — it&rsquo;s end-to-end encrypted via XMTP.</li>
              <li>We do not share wallet addresses beyond what&rsquo;s publicly visible on listings and the blockchain.</li>
              <li>We do not use analytics services that track user behavior.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">6. Third-Party Services</h2>
            <p>TruCheq integrates with the following third-party services. Each has its own privacy policy:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>World ID / IDKit</strong> — Identity verification (worldcoin.org/privacy)</li>
              <li><strong>XMTP</strong> — End-to-end encrypted messaging (xmtp.org/privacy)</li>
              <li><strong>Filebase / IPFS</strong> — Decentralized storage (filebase.com/privacy)</li>
              <li><strong>Coinbase x402</strong> — Payment protocol (coinbase.com/privacy)</li>
              <li><strong>World App / MiniKit</strong> — Mini App hosting and wallet connection.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">7. Data Retention &amp; Deletion</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Local data</strong> — can be deleted at any time via the in-app logout function or by clearing browser data.</li>
              <li><strong>IPFS data</strong> — once uploaded, listing data may persist on the IPFS network even if TruCheq stops pinning it. We cannot guarantee deletion of data from the IPFS network.</li>
              <li><strong>Blockchain data</strong> — transaction records on Base and World Chain are immutable and cannot be deleted.</li>
              <li><strong>XMTP messages</strong> — encrypted message history is managed by the XMTP network and cannot be deleted by TruCheq.</li>
              <li><strong>World ID data</strong> — verification records are managed by World ID and subject to their privacy policy.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">8. Security</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>End-to-end encryption for all buyer-seller communication via XMTP.</li>
              <li>Zero-knowledge proofs for identity verification (World ID).</li>
              <li>No server-side storage of user data — all state is on IPFS, blockchain, or local storage.</li>
              <li>Wallet private keys never leave the user&rsquo;s device or wallet app.</li>
            </ul>
            <p>While we strive to protect your privacy, no system is completely secure. You are responsible for safeguarding your wallet credentials and device access.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">9. Children&rsquo;s Privacy</h2>
            <p>TruCheq is not intended for use by individuals under the age of 18. We do not knowingly collect data from children. If you believe a minor has used the Service, please contact us.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">10. International Users</h2>
            <p>TruCheq is a decentralized protocol accessible globally. By using the Service, you acknowledge that your data may be processed on blockchain networks and IPFS nodes located in various jurisdictions. You are responsible for ensuring your use complies with local laws.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">11. Changes to This Policy</h2>
            <p>We may update this Privacy Policy from time to time. We will update the &ldquo;Last updated&rdquo; date. Continued use of the Service after changes constitutes acceptance of the revised Policy.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-black text-white tracking-tight">12. Contact</h2>
            <p>For privacy-related questions or concerns, contact us through the TruCheq community channels or open an issue on our repository.</p>
          </section>
        </div>

        <div className="pt-8 border-t border-white/10 text-center space-y-4">
          <Link href="/terms">
            <Button variant="outline" className="rounded-xl border-white/10 hover:bg-white/5 mr-2">
              Terms of Service
            </Button>
          </Link>
          <Link href="/">
            <Button variant="outline" className="rounded-xl border-white/10 hover:bg-white/5">
              <LucideArrowLeft className="w-4 h-4 mr-2" />
              Return to TruCheq
            </Button>
          </Link>
        </div>
      </div>
    </main>
  );
}
